_wandb:
    value:
        cli_version: 0.25.1
        e:
            c5af9evksax3pbd8nap6w3mt3c6vzr44:
                args:
                    - --output-dir
                    - NaOH_7.5M/visnet/runs/visnet_1
                    - --epochs
                    - "100"
                    - --batch-size
                    - "8"
                    - --lr
                    - "0.0001"
                    - --num-layers
                    - "6"
                    - --cutoff
                    - "6.0"
                    - --device
                    - cuda
                    - --wandb
                    - --wandb-project
                    - naoh-visnet-eip
                    - --wandb-name
                    - visnet_1
                    - --build-edges-if-missing
                    - --early-stopping-monitor
                    - val/force_mae
                    - --edge-data
                    - NaOH_7.5M/data/visnet/na12_ab_edges_cutoff6.0.pt
                    - --max-num-neighbors
                    - "64"
                codePath: NaOH_7.5M/visnet/train.py
                codePathLocal: NaOH_7.5M/visnet/train.py
                email: 253107030016@sii.edu.cn
                executable: /root/miniconda3/envs/ED/bin/python
                git:
                    commit: 3294a11f32f12c362fafe05070c95038ed365f8f
                    remote: https://github.com/huiligroup/SFG_NaOH.git
                host: ed2--f95842662433-jsjusigvyr
                os: Linux-5.15.0-141-generic-x86_64-with-glibc2.35
                program: /inspire/ssd/project/materialscienceresearch/tanghaoyu-253107030016/SFG_NaOH/NaOH_7.5M/visnet/train.py
                python: CPython 3.10.20
                root: NaOH_7.5M/visnet/runs/visnet_1
                startedAt: "2026-05-01T19:25:12.950020Z"
                writerId: c5af9evksax3pbd8nap6w3mt3c6vzr44
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 8
batches_per_step:
    value: 100
build_edges_if_missing:
    value: true
cutoff:
    value: 6
data:
    value: /inspire/ssd/project/materialscienceresearch/tanghaoyu-253107030016/SFG_NaOH/NaOH_7.5M/data/visnet/na12_ab.pkl
device:
    value: cuda
early_stopping_min_delta:
    value: 0
early_stopping_monitor:
    value: val/force_mae
early_stopping_patience:
    value: 20
edge_build_limit:
    value: null
edge_data:
    value: NaOH_7.5M/data/visnet/na12_ab_edges_cutoff6.0.pt
epochs:
    value: 100
force_weight:
    value: 1
frame_stride:
    value: 4
grad_clip:
    value: 10
hidden_channels:
    value: 64
limit_batches:
    value: null
limit_frames:
    value: null
limit_val_batches:
    value: null
lr:
    value: 0.0001
max_num_neighbors:
    value: 64
no_val:
    value: false
num_heads:
    value: 8
num_layers:
    value: 6
num_rbf:
    value: 32
output_dir:
    value: NaOH_7.5M/visnet/runs/visnet_1
quantile:
    value: 0.5
reg_weight:
    value: 0.01
val_interval_steps:
    value: 10
wandb:
    value: true
wandb_entity:
    value: null
wandb_mode:
    value: online
wandb_name:
    value: visnet_1
wandb_project:
    value: naoh-visnet-eip
wandb_watch:
    value: false
wandb_watch_log:
    value: gradients
