_wandb:
    value:
        cli_version: 0.25.1
        e:
            p2so36t80d6hii91kyywy9fhv1dkn2b4:
                args:
                    - --output-dir
                    - NaOH_7.5M/visnet/runs/visnet_2
                    - --epochs
                    - "300"
                    - --hidden-channels
                    - "128"
                    - --batch-size
                    - "4"
                    - --lr
                    - "0.0001"
                    - --num-layers
                    - "9"
                    - --cutoff
                    - "6.0"
                    - --device
                    - cuda
                    - --wandb
                    - --wandb-project
                    - naoh-visnet-eip
                    - --wandb-name
                    - visnet_2
                    - --build-edges-if-missing
                    - --early-stopping-monitor
                    - val/force_mae
                    - --edge-data
                    - NaOH_7.5M/data/visnet/na12_ab_edges_cutoff6.0.pt
                    - --max-num-neighbors
                    - "64"
                codePath: NaOH_7.5M/visnet/train.py
                codePathLocal: NaOH_7.5M/visnet/train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3838880616448"
                        used: "2139580108800"
                email: 253107030016@sii.edu.cn
                executable: /root/miniconda3/envs/ED/bin/python
                git:
                    commit: 3294a11f32f12c362fafe05070c95038ed365f8f
                    remote: https://github.com/huiligroup/SFG_NaOH.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-7beba04e-581e-6b99-ab8d-3609aaee254f
                host: ed2--f95842662433-jsjusigvyr
                memory:
                    total: "1081541984256"
                os: Linux-5.15.0-141-generic-x86_64-with-glibc2.35
                program: /inspire/ssd/project/materialscienceresearch/tanghaoyu-253107030016/SFG_NaOH/NaOH_7.5M/visnet/train.py
                python: CPython 3.10.20
                root: NaOH_7.5M/visnet/runs/visnet_2
                startedAt: "2026-05-03T00:45:10.736365Z"
                writerId: p2so36t80d6hii91kyywy9fhv1dkn2b4
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 4
batches_per_step:
    value: 100
build_edges_if_missing:
    value: true
cutoff:
    value: 6
data:
    value: /inspire/ssd/project/materialscienceresearch/tanghaoyu-253107030016/SFG_NaOH/NaOH_7.5M/data/visnet/na12_ab.pkl
device:
    value: cuda
early_stopping_min_delta:
    value: 0
early_stopping_monitor:
    value: val/force_mae
early_stopping_patience:
    value: 20
edge_build_limit:
    value: null
edge_data:
    value: NaOH_7.5M/data/visnet/na12_ab_edges_cutoff6.0.pt
epochs:
    value: 300
force_weight:
    value: 1
frame_stride:
    value: 4
grad_clip:
    value: 10
hidden_channels:
    value: 128
limit_batches:
    value: null
limit_frames:
    value: null
limit_val_batches:
    value: null
lr:
    value: 0.0001
max_num_neighbors:
    value: 64
no_val:
    value: false
num_heads:
    value: 8
num_layers:
    value: 9
num_rbf:
    value: 32
output_dir:
    value: NaOH_7.5M/visnet/runs/visnet_2
quantile:
    value: 0.5
reg_weight:
    value: 0.01
val_interval_steps:
    value: 10
wandb:
    value: true
wandb_entity:
    value: null
wandb_mode:
    value: online
wandb_name:
    value: visnet_2
wandb_project:
    value: naoh-visnet-eip
wandb_watch:
    value: false
wandb_watch_log:
    value: gradients
